# Generated by Django 5.1.7 on 2025-03-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('languages', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=2088)),
            ],
        ),
    ]
